name: "PR Sync"

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      
jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest

    steps:
    - name: Get data
      run: |
        echo $GITHUB_EVENT_PATH
        cat $GITHUB_EVENT_PATH
        exit 1
